SSallometric Self-starting version of the allometric function y = a x^b.
### Description
This function is used for fitting the allometric function to bivaraite data. The function is of the form
y = alpha x ^ beta, where traditionally x and y are different dimensions of a sampling unit, such as
diameter and volume of a tree.

### Usage
<pre><code>
SSallometric(x, alpha, beta)
</code></pre>
### Arguments
x predictor variable (e.g. volume)
alpha product parameter
beta exponent parameter
### Value
* The function returns a numeric vector of response variables. 
* The vector has two additional attributes: the gradient, which reports the first derivative of the function with respect to the parameters,
evaluated at the response ### Value; and the hessian, which reports the matrix of second partial
derivatives of the function with respect to the parameters evaluated at the response variable.
* Note: Demonstrates construction and usage of self-starting functions using selfStart.

### References
Robinson, A.P., and J.D. Hamann. 2010. Forest Analytics with R: an Introduction. Springer.

### See Also
selfStart
### Examples
```{r}
SSallometric(10, 2, 3)
data(sweetgum)
nls(vol.m3 ~ SSallometric(dbh.cm, alpha, beta), data = sweetgum)
```
