Package ‘forestmangr’
October 26, 2018
Type Package
Version 0.9.0
Title Functions for Forest Mensuration and Management
#### Description Set of functions for processing forest inventory data with methods such as simple random
sampling, stratified random sampling and systematic sampling. There are also functions
for yield and growth predictions and model fitting, linear and non linear grouped data fitting
functions, and statistical tests.
Author Sollano Rabelo Braga [aut, cre, cph],
Marcio Leles Romarco de Oliveira [aut],
Eric Bastos Gorgens [aut]
Maintainer Sollano Rabelo Braga <sollanorb@gmail.com>
Depends R(>= 3.3)
Imports dplyr(>= 0.7.0), ggplot2(>= 2.0), ggthemes, tidyr, broom,
scales(>= 0.4.1), psych, purrr, plyr, tibble, systemfit,
htmltools, ggpmisc, rlang, graphics, utils, covr, rmarkdown,
curl, car, stats, methods,magrittr,minpack.lm
Suggests
Date 2018-10-15
Encoding UTF-8
License GPL-2
RoxygenNote 6.1.0
NeedsCompilation no
Repository CRAN
Date/Publication 2018-10-26 14:30:05 UTC
R topics documented:
average_tree_curve . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
bdq_meyer . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
bias_per . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
1
2 R topics documented:
check_names . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
classify_site . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
diameter_class . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
dom_height . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
est_clutter . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
exfm1 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
exfm10 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14
exfm11 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
exfm12 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
exfm13 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 16
exfm14 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
exfm15 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 17
exfm16 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
exfm17 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 18
exfm18 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 19
exfm19 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 20
exfm2 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21
exfm20 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 21
exfm21 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 22
exfm3 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 23
exfm4 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 24
exfm5 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 24
exfm6 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 25
exfm7 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 26
exfm8 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 27
exfm9 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 27
fit_clutter . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 28
forest_structure . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 30
Graybill_F . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 31
guide_curve . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 32
huberwb . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 34
huberwob . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 35
ident_model . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 37
inv . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 39
lm_table . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 40
nls_table . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 42
plot_summarise . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 45
pow . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 47
resid_plot . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 48
rmse_per . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 49
round_df . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 51
similarity_matrix . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 52
smalianwb . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 53
smalianwob . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 54
species_aggreg . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 56
species_diversity . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 57
sprs . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 58
ss_diffs . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 60
average_tree_curve 3
strs . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 62
tree_summarise . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 64
vertical_stratum . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 65
vol_summarise . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 66
%>% . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 67
%T>% . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 67
Index 68





vertical_stratum Divide data into 3 vertical strata
#### Description
Get the vertical strata of data based on the height variable. The data will be divided into inferior,
medium and superior strata.
#### Usage
vertical_stratum(df, th)
#### Arguments 
*``df``: A data frame.
th Quoted name of the total height variable.
Value
a data frame.
Author(s)
Eric Bastos Gorgens <e.gorgens@gmail.com>
#### References
Souza, A. L. and Soares, C. P. B. (2013) Florestas Nativas: estrutura, dinamica e manejo. Vicosa:
UFV.
66 vol_summarise
#### Examples
library(forestmangr)
data(exfm10)
# To classify the data, supply the data frame and the height variable name:
vertical_stratum(exfm10, "TH" )
vol_summarise Summarize volume of trees
#### Description
This function can be used to summarize volume with and without bark of trees in a data frame.
#### Usage
vol_summarise(df, dbh, th, vwb, tree, .groups = NA, vwob = NA)
#### Arguments 
*``df``: A data frame.
* ``dbh``: Quoted nameof the diameter at breast height variable, in cm.
th Quoted name of the total height variable, in meters.
vwb Quoted name of the volume with bark variable, in cubic meters.
tree Quoted name of the tree variable. used to differentiate the trees’ sections. If this
argument is NA, the defined groups in the data frame will be used. Default: NA.
* ``.groups``: Optional argument. Quoted name(s) of additional grouping variables that can be
added to differentiate subdivisions of the data.
vwob Optional argument. Quoted name of the volume without bark variable, in cubic
meters. Default: NA. If this argument is NA, the defined groups in the data frame
will be used. Default: NA.
Value
A data frame summarized by the .groups variable(s).
Author(s)
Sollano Rabelo Braga <sollanorb@gmail.com>
See Also
Complementary functions: smalianwb, For calculation of volume with bark using the Smalian
method, smalianwob, For calculation of volume without bark using the Smalian method, huberwb,
for calculation of volume with bark using the Huber method, huberwob, for calculation of volume
without bark the Huber method.
%>% 67
#### Examples
library(forestmangr)
data("exfm7")
head(exfm7)
# In order to calculate the volume of each tree, first we
# Calculate the volume by tree section using the Smalian method:
sec_data_vol <- exfm7 %>%
smalianwb("di_wb", "hi", "TREE") %>%
smalianwob("di_wb", "hi", "bark_t", "TREE", bt_mm_to_cm = TRUE)
sec_data_vol
# Now, we summarize the tree's volume:
vol_summarise(sec_data_vol, dbh = "DBH", th = "TH", vwb = "VWB",
tree = "TREE", .groups = "STRATA",vwob = "VWOB")
# It's possible to do everything using pipes:
exfm7 %>%
smalianwb("di_wb", "hi", "TREE") %>%
smalianwob("di_wb", "hi", "bark_t", "TREE", bt_mm_to_cm = TRUE) %>%
vol_summarise("DBH", "TH", "VWB", "TREE", "STRATA", "VWOB")
%>% Pipe
#### Description
Pipe an object forward into a function or call expression. See magrittr for more #### Details.
See quasiquotation for more #### Details.
%T>% Tee
#### Description
Pipe an object forward into a function or call expression. See magrittr for more #### Details.
