forest_structure Get the forest horizontal, vertical and internal structure
#### Description
This function calculates the horizontal structure of a given forest inventory data, with information
like absolute frequency, relative frequency, absolute density, relative density, absolute dominance,
relative dominance, importance value index, and coverage value index. If additional variables are
supplied, the vertical and internal structures are also provided.
#### Usage
forest_structure(df, species, dbh, plot, plot_area, vertical_est = NA,
internal_est = NA, NI_label = "")

#### Arguments 
*``df``: A data frame.
species Quoted name of the scientific names variable, or any variable used to differentiate
the different species found in data.
* ``dbh``: Quoted nameof the diameter at breast height variable, in cm.
* ``plot``:  Quoted name of the plot variable. used to differentiate the plot’s trees, and
calculate the number of sampled plots.
* `` plot_area``:  Quoted name of the plot area variable, or a numeric vector with the plot area
value. The plot area value must be in square meters.
vertical_est Optional argument. Quoted name of the vertical strata variable, or the height
variable. If this is a factor variable, it’s levels will be used to classify the forest vertically. If it’s a height variable, the vertical strata will be created based on it’s
mean and standard deviation values. Default: NA.
internal_est Optional argument. Quoted name of the internal strata variable. Default: NA.
NI_label Label used for Species not identified. This parameter works along with species.
The level supplied here will not be considered in the classification. Default "".

#### Value
a data frame with the forest’s structure.
Author(s)
Eric Bastos Gorgens <e.gorgens@gmail.com>

#### References
Souza, A. L. and Soares, C. P. B. (2013) Florestas Nativas: estrutura, dinamica e manejo. Vicosa:
UFV.
Graybill_F 31

#### Examples
```{r}
library(forestmangr)
data(exfm20)
# Get the forest's horizontal structure:
forest_structure(exfm20, "scientific.name", "dbh", "transect", 10000)
# area plot as a variable name:
forest_structure(exfm20, "scientific.name", "dbh", "transect", "plot.area")
# Get the forest's horizontal and vertical structure.
# The vertical structure variable can either be the height variable,
# or a factor variable with the horizontal strata:
forest_structure(exfm20, "scientific.name", "dbh", "transect", 10000, "canopy.pos")
# Get the forest's horizontal, vertical and internal structure:
forest_structure(exfm20, "scientific.name", "dbh", "transect", 10000, "canopy.pos", "light")

```
