
## gutten 
gutten von Guttenberg’s Norway spruce (Picea abies [L.] Karst) tree measurement
data.
### Description
The data are measures from 107 trees. The trees were selected as being of average size from healthy
and well stocked stands in the Alps.

### Usage
<pre><code>
data(gutten)
</code></pre>

### Format
A data frame with 1200 observations on the following 9 variables.
* ``site`` Growth quality class of the tree’s habitat. 5 levels.
* ``location`` Distinguishes tree location. 7 levels.
* ``tree``   An identifier for the tree within location.
* ``age.base`` The tree age taken at ground level.
* ``height`` Tree height, m.
* ``dbh.cm``: Tree diameter, cm.
* ``volume`` Tree volume.
* ``age.bh`` Tree age taken at 1.3 m.
* ``tree.ID`` A factor uniquely identifying the tree.

### Examples
```{r}
data(gutten)
str(gutten)
```

### Source
* The data were kindly provided to us by Professor Boris Zeide, and are documented in von Guttenberg,
A. R., 1915. Growth and yield of spruce in Hochgebirge. Franz Deuticke, Vienna (in
German).

### References
* Robinson, A.P., and J.D. Hamann. 2010. Forest Analytics with R: an Introduction. Springer.
* Zeide, B., 1993. Analysis of growth equations. Forest Science 39 (3), 549-616


