
## ``herbdata`` 
Herbicide trial seedling data

### Description
These data were collected during the 1994 planting season in Southwest Washington State.

### Usage
<pre><code>
data(herbdata)
</code></pre>

### Format
A data frame with 961 observations on the following 8 variables.
* ``treat``: treatment for control or application
* ``rep``: replication
* ``tree``: tree number in the replication
* ``date``: date the observation was made
* ``isalive``: indicator for alive/dead status
* ``height``: height of the tree in cm
* ``dia``: basal diameter of the stem, in mm
* ``dbh``: diameter at breast height, in mm

### Examples
```{r}
data(herbdata)
```

### Details
* The plots were installed during the 1994 planting season in southwestern Washington by Don Wallace
and Bruce Alber. Three replications of 20 seedlings were planted in two blocks. 
* The two blocks were a control block and a block treated with 220 ml per hectare of Oust herbicide. The
plots were then measured over the next ten years. 
& At each observation, the basal diameter, total
height, and condition of the stem were recorded. When the stems reached breast height (1.37 m in
the United States), the breast height diameter was also recorded. 
* An indicator variable was used to
record if the stem was dead or alive. If the stem was dead, the observations were recorded as NA.

### Source
* The data are provided courtesy of Don Wallace and Bruce Alber of the Wilbur-Ellis Company.

### References
* Robinson, A.P., and J.D. Hamann. 2010. Forest Analytics with R: an Introduction. Springer.


