## ufc 
Upper Flat Creek forest cruise tree data

### Description
These are a subset of the tree measurement data from the Upper Flat Creek unit of the University of
Idaho Experimental Forest, which was measured in 1991.

### Usage
<pre><code>
data(ufc)
</code></pre>
###Format
A data frame with 336 observations on the following 5 variables.
* ``plot``: plot label
* ``tree``: tree label
* ``species``: species kbd with levels DF, GF, WC, WL
* ``dbh.cm``: Tree diameter at 1.37 m. from the ground, measured in centimetres.
* ``height.m``: tree height measured in metres

### Details
* The inventory was based on variable radius plots with 6.43 sq. m. per ha. BAF (Basal Area Factor).
* The forest stand was 121.5 ha. This version of the data omits errors, trees with missing heights,
and uncommon species. 
* The four species are Douglas-fir, grand fir, western red cedar, and western
larch.
* Source: The data are provided courtesy of Harold Osborne and Ross Appelgren of the University of Idaho
Experimental Forest.
### References
Robinson, A.P., and J.D. Hamann. 2010. Forest Analytics with R: an Introduction. Springer.
### Examples
data(ufc)
