Package ‘growthmodels’
February 20, 2015
Type Package
Title Nonlinear Growth Models
Version 1.2.0
Date 2013-11-23
Author Daniel Rodriguez Perez
Maintainer Daniel Rodriguez Perez <daniel.rodriguez.perez@gmail.com>
Description A compilation of nonlinear growth models used in many areas
License GPL-3
URL https://github.com/drodriguezperez/growthmodels
BugReports https://github.com/drodriguezperez/growthmodels/issues
Collate 'negativeExponential.R' 'monomolecular.R' 'mitcherlich.R'
'gompertz.R' 'logistic.R' 'chapmanRichards.R' 'richard.R'
'vonBertalanffy.R' 'weibull.R' 'loglogistic.R' 'mmf.R'
'schnute.R' 'stannard.R' 'brody.R' 'growthmodels.R'
'blumberg.R'
NeedsCompilation no
Repository CRAN
Date/Publication 2013-11-23 17:11:06
R topics documented:
growthmodels-package . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 2
blumberg . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 3
brody . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
chapmanRichards . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 4
generalisedLogistic . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 5
generalisedRichard . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 6
gompertz . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 7
logistic . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
loglogistic . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 8
mitcherlich . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 9
1
2 growthmodels-package
mmf . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 10
monomolecular . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
negativeExponential . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 11
richard . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 12
schnute . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 13
stannard . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14
vonBertalanffy . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 14
weibull . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 15
Index 17
growthmodels-package growthmodels: Nonlinear Growth Models
Description
A compilation of nonlinear growth models used in many areas.
Details
Package: growthmodels
Version: 1.2.0
License: GPL-3
Author(s)
Daniel Rodriguez Perez <daniel.rodriguez.perez@gmail.com>
### References
D. Fekedulegn, M. Mac Siurtain, and J. Colbert, "Parameter estimation of nonlinear growth models
in forestry," Silva Fennica, vol. 33, no. 4, pp. 327-336, 1999.
M. M. Kaps, W. O. W. Herring, and W. R. W. Lamberson, "Genetic and environmental parameters
for traits derived from the Brody growth curve and their relationships with weaning weight in Angus
cattle.," Journal of Animal Science, vol. 78, no. 6, pp. 1436-1442, May 2000.
A. Tsoularis and J. Wallace, "Analysis of logistic growth models.," Math Biosci, vol. 179, no. 1,
pp. 21-55, Jul. 2002.
A. Khamiz, Z. Ismail, and A. T. Muhammad, "Nonlinear growth models for modeling oil palm yield
growth," Journal of Mathematics and Statistics, vol. 1, no. 3, p. 225, 2005.
http://en.wikipedia.org/wiki/Generalised_logistic_function
blumberg 3
blumberg Blumberg growth model
Description
Computes the Blumberg growth model and its inverse
y(t) =
  (t + t0)m
w0 + (t + t0)m
### Usage <pre><code>
blumberg(t, alpha, w0, m, t0 = 0)
blumberg.inverse(x, alpha, w0, m, t0 = 0)
### Arguments 
*``t``: time
*``x``: size
*``alpha``: upper asymptote
w0 a reference value at t = t0
m slope of growth
t0 time shift (default 0)
### References
A. Tsoularis and J. Wallace, "Analysis of logistic growth models.," Math Biosci, vol. 179, no. 1,
pp. 21-55, Jul. 2002.
### Examples
growth <- blumberg(0:10, 10, 2, 0.5)
# Calculate inverse function
time <- blumberg.inverse(growth, 12, 2, 0.5)
4 chapmanRichards
brody Brody growth model
Description
Computes the Brody growth model and its inverse
y(t) =  ?? ( ?? w0)exp(??kt)
### Usage <pre><code>
brody(t, alpha, w0, k)
brody.inverse(x, alpha, w0, k)
### Arguments 
*``t``: time
*``x``: size
*``alpha``: upper asymptote
w0 the value at t = 0
*``k``: growth rate
### References
M. M. Kaps, W. O. W. Herring, and W. R. W. Lamberson, "Genetic and environmental parameters
for traits derived from the Brody growth curve and their relationships with weaning weight in Angus
cattle.," Journal of Animal Science, vol. 78, no. 6, pp. 1436-1442, May 2000.
### Examples
growth <- brody(0:10, 10, 5, 0.3)
# Calculate inverse function
time <- brody.inverse(growth, 10, 5, 0.3)

