FI
Forest inventory equations and calculations with FI
Description
That package was created because I can’t find any free solution for these basic calculations also will
serve as learning experience to create packages in R.
Details
Here I implement the three basic volume equations (Smalian, Newton, Huber) and form and stack-
ing factors. From these you can gather many information about a region log volume (mean and
standard deviation). Later a new package will provide volumetric equations adjust.
See Also
volumeinventory
inventory
3
Example of how object tree in volume function should be formated
Description
Choice of that format follow similarity with cubmaster for simplify user translation of work (export-
ing old tables). Names of columns are just cosmetic, currently I use column index. All diameters
mensures should rather be in centimeters and heights in meters
Format
A data frame with 17 rows and 6 variables
Details
• tree_number. unique number to identify tree information
• dbh. diameter at breast height
• total_height. total height of the tree. Unsed parameter in volume
• commercial_height. commercial height of tree. Unsed parameter in volume
• section_height. height of each section where diameter section is taken
• section_diameter. diameter in current height
Stacking factor
sf
Description
Ratio between solid cubic meters of wood per stere cubic meter of stacked up wood.
Usage
sf(volume, height, length, depth)
Arguments
volume real volume of the logs
height height of the stack (in meters)
length length of the stack (in meters)
depth depth of the stack (in meters)
Value
stacking factor ranging from 0-14
volume
References
www.eucalyptus.com.br/capitulos/ENG07.pdf
volume
Estimates the stem volume
Description
volume uses one of the following methods (Smalian, Newton, Huber) to approximate real stem
volume. Users should remember they’re just approximations and sample size provide more accurate
results them using different methods.
Usage
volume(trees, method = "smalian")
Arguments
trees a data frame or matrix in format described in dataset inventory (more help
inventory)
method method used for estimation of the stem volume
Value
a named vector of volumes, names are defined as same as in first column
Note
Newton and Huber methods have small modifications for working just with two mensures (lower
and upper diameter). Both of them use mean instead of real middle diameter.
References
http://wiki.awf.forst.uni-goettingen.de/wiki/index.php/Stem_volume
See Also
ff sf
Examples
example_data <- data.frame(tree_number = 1,
dhb = 5,
total_height = 20,
comercial_height = 15,
section_height = c(0,5,15),
section_diameter = 5
)volume
volume(example_data)
#
#
# A little more complex and common example
data(inventory)
volume_output <- volume(inventory)
summary(volume_output)
hist(volume_output)
5Index
∗Topic datasets
inventory, 3
ff, 1, 4
FI, 2
FI-package (FI), 2
inventory, 3, 4
sf, 3, 4
volume, 2, 3, 4
6
