---
title: "Untitled"
author: "Kevin O Brien"
date: "28 November 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

DBH Trees height and diameter at breast height

#### Description

The DBH data contains the diameter at breast height (dbh), height and condition data for all trees
centered in 108 plots of size 0.2 hectare immediately following a single prescribed burn and also
following three 5-yr (year) interval reburns (four burns total) and a single 15-yr interval reburn
(two burns total) and associated treatment information. The trees information were established
from mixed ponderosa pine (Pinus ponderosa Dougl. ex Laws.) that contained scattered western
junipers (Juniperus occidentalis Hook.). The plots were located in the Malheur National Forest on
the southern end of the Blue Mountains near Burns, Oregon, USA.

#### Usage

data(DBH)
Format
A text file with 5732 observations from 17 variables related of trees characteristics such as dbh and
height.
