---
title: "References"
author: "Kevin O Brien"
date: "28 November 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

````

#### References

G. J. McLachlan and T. Krishnan, 2007. The EM Algorithm and Extensions, John Wiley & Sons.
A. P. Dempster, N. M. Laird, and D. B. Rubin, 1977. Maximum likelihood from incomplete data
via the EM algorithm, Journal of the Royal Statistical Society, Series B (methodological), 1-38.
M. Teimouri and A. K. Gupta, 2012. Estimation Methods for the Gompertz-Makeham Distribution
Under Progressively Type-I Interval Censoring Scheme, National Academy Science Letters, 35(3).

#### References

E. J. Green, F. A. R. Jr, A. F. M. Smith, and W. E. Strawderman, 1994. Bayesian estimation for the
three-parameter Weibull distribution with tree diameter data, Biometrics, 50(1), 254-269.

#### References

J. W. Flewelling and R. De Jong. (1994). Considerations in simultaneous curve fitting for repeated
height-diameter measurements, Canadian Journal of Forest Research, 24(7), 1408-1414.
S. Huang, S. J. Titus, and D. P. Wiens. 1992. Comparison of nonlinear height±diameter functions
for major Alberta tree species. Canadian Journal of Forest Research, 22, 1297-1304.
R. Pearl and L. J. Reed. (1920). On the rate of growth of the population of the United States since
1790 and its mathematical representation, Proceedings of the National Academy of Sciences of the
United States of America, 6(6), 275.
M. Prodan. 1968. The spatial distribution of trees in an area. Allg. Forst Jagdztg, 139, 214-217.
D. A. Ratkowsky. 1990. Handbook of nonlinear regression, New York, Marcel Dekker, Inc.
F. J. Richards. 1959. A flexible growth function for empirical use. Journal of Experimental Botany,
10, 290-300.
S. B. Winsor. 1992. The Gompertz curve as a growth curve. Proceedings of National Academic
Science, USA, 18, 1-8.
R. C. Yang, A. Kozak, J. H. G. Smith. 1978. The potential of Weibull-type functions as a flexible
growth curves. Canadian Journal of Forest Research, 8, 424-431.
B. Zeide. 1993. Analysis of growth equation. Forest Science, 39, 594-616.

Source
B. K., Kerns, D. J., Westlind, and M. A. Day. 2017. Season and interval of burning and cattle
exclusion in the southern blue mountains, oregon: Overstory tree height, diameter and growth.
Forest Service Research Data Archive, https://doi.org/10.2737/RDS-2017-0041.

#### References

B. K., Kerns, D. J., Westlind, and M. A. Day. 2017. Season and interval of burning and cattle
exclusion in the southern blue mountains, oregon: Overstory tree height, diameter and growth.
Forest Service Research Data Archive, https://doi.org/10.2737/RDS-2017-0041.
dgsm Computing probability density function of the gamma shape mixture
model


#### References

A. P. Dempster, N. M. Laird, and D. B. Rubin, 1977. Maximum likelihood from incomplete data
via the EM algorithm, Journal of the Royal Statistical Society Series B, 39, 1-38.

S. Venturini, F. Dominici, and G. Parmigiani, 2008. Gamma shape mixtures for heavy-tailed distributions,
The Annals of Applied Statistics, 2(2), 756-776.


#### References

A. Azzalini, 1985. A class of distributions which includes the normal ones, Scandinavian Journal
of Statistics, 12, 171-178.
A. P. Dempster, N. M. Laird, and D. B. Rubin, 1977. Maximum likelihood from incomplete data
via the EM algorithm, Journal of the Royal Statistical Society Series B, 39, 1-38.
M. Teimouri, S. Rezakhah, and A. Mohammdpour, 2018. EM algorithm for symmetric stable
mixture model, Communications in Statistics-Simulation and Computation, 47(2), 582-604.

#### References

N. L. Johnson, 1949. Systems of frequency curves generated by methods of translation, Biometrika,
36, 149-176.
L. J. Norman, S. Kotz, and N. Balakrishnan, 1994. Continuous Univariate Distributions, volume I,
John Wiley & Sons.

#### References

S. Venturini, F. Dominici, and G. Parmigiani, 2008. Gamma shape mixtures for heavy-tailed distributions,
The Annals of Applied Statistics, 2(2), 756-776.


#### References

R. C. H. Cheng and M. A. Stephens, 1989. A goodness-of-fit test using Moran's statistic with
estimated parameters, Biometrika, 76(2), 385-392.
C. A. Clifford and B. Whitten, 1982. Modified maximum likelihood and modified moment estimators
for the three-parameterWeibull distribution, Communication in Statistics-Theory and Methods,
11(23), 2631-2656.
D. Cousineau, 2009. Nearly unbiased estimators for the three-parameter Weibull distribution with
greater efficiency than the iterative likelihood method, British Journal of Mathematical and Statistical
Psychology, 62, 167-191.

#### References

G. J. McLachlan and P. N. Jones, 1988. Fitting mixture models to grouped and truncated data via
the EM algorithm, Biometrics, 44, 571-578

G. Cran, 1988. Moment estimators for the 3-parameter Weibull distribution, IEEE Transactions on
Reliability, 37(4), 360-363.
J. R. Hosking, 1990. L-moments: analysis and estimation of distributions using linear combinations
of order statistics, Journal of the Royal Statistical Society. Series B (Methodological), 52(1), 105-
124.
Y. M. Kantar, 2015. Generalized least squares and weighted least squares estimation methods for
distributional parameters, REVSTAT-Statistical Journal, 13(3), 263-282.
M. Teimouri and S. Nadarajah, 2012. A simple estimator for the Weibull shape parameter, International
Journal of Structural Stability and Dynamics, 12(2), 2395-402.
M. Teimouri, S. M. Hoseini, and S. Nadarajah, 2013. Comparison of estimation methods for the
Weibull distribution, Statistics, 47(1), 93-109.
F. Wang and J. B. Keats, 1995. Improved percentile estimation for the two-parameter Weibull
distribution, Microelectronics Reliability, 35(6), 883-892.
L. Zhang, M. Xie, and L. Tang, 2008. On Weighted Least Squares Estimation for the Parameters
of Weibull Distribution. In: Pham H. (eds) Recent Advances in Reliability and Quality in Design.
Springer Series in Reliability Engineering. Springer, London.
