wind.data
Wind data example
#### Description

This is an example of wind data obtained with wind.dl function for the Iberian Peninsula coorde-
nates on 12/February/2015 at 00:00 (UTC)
Format
A list with one data.frame with 651 observations on the following 7 variables:
list("time (UTC)") a numeric with selected time of wind data
list("latitude (degrees_north)") a numeric with latitude values
list("longitude (degrees_east)") a numeric with longitude values
list("ugrd10m (m s-1)") a numeric with U component of wind data
list("vgrd10m (m s-1)") a numeric with V component of wind data
list("dir") a numeric with direction of wind data
list("speed") a numeric with speed of wind data8
wind.dl
#### Details 
 
This data set is the result of:
wind.data <- wind.dl(2015,2,12,0,-10,5,35,45)
Source
http://allthiswasfield.blogspot.com.es/2016/12/rwind-r-package-released.html

#### References 
 
http://oos.soest.hawaii.edu/erddap/info/NCEP_Global_Best/index.html
#### Examples
 ```{r}
data(wind.data)
str(wind.data)
head(wind.data[[1]])
