rWind-package

Download, edit and include wind data in ecological and evolutionary
analysis
#### Description

rWind contain tools for downloading, editing and transforming wind data from Global Forecast
System (GFS). It also allows to use wind data to compute the minimum cost path from wind speed
and direction to perform connectivity analysis.
#### Details 
 
The complete list of functions can be displayed with library(help = rWind). For more informa-
tion, please check: http://allthiswasfield.blogspot.com.es/

#### Author(s) 
 
Javier Fernández-López
Klaus Schliep
Maintainer: Javier Fernández-López <jflopez.bio@gmail.com>
arrowDir
Arrow direction fitting for Arrowhead function from "shape" package
#### Description

arrowDir adapts wind direction value to be used by Arrowhead function from "shape" package to
plot wind direction for each coordinate.
Usage
arrowDir(W)arrowDir
3
Arguments
W
An object of class rWind or a data.frame which should content a column named
"dir".
#### Details 
 
Angle argument of Arrowhead function from "shape" package needs to be fed in an anti-clockwise
way, relative to x-axis, in degrees [0,360]. arrowDir function adapts wind direction provided by
wind.fit (clockwise, relative to y-axis ) to requirements of Arrowhead.
#### Value

A vector with angles for each arrow to be plotted by Arrowhead.
Note
arrowDir function works always together with Arrowhead function from "shape" package.

#### Author(s) 
 
Javier Fernández-López

#### References 
 
Karline Soetaert (2017). shape: Functions for Plotting Graphical Shapes, Colors. R package version
1.4.3. https://CRAN.R-project.org/package=shape
See Also
wind.dl
#### Examples
 ```{r}
data(wind.data)
# Create a vector with wind direction (angles) adapted
alpha <- arrowDir(wind.data)
## Not run:
# Now, you can plot wind direction with Arrowhead function from shapes package
# Load "shape package
require(shape)
plot(wind.data$lon, wind.data$lat, type="n")
Arrowhead(wind.data$lon, wind.data$lat, angle=alpha,
arr.length = 0.1, arr.type="curved")
## End(Not run)4
