cost.FMGS
cost.FMGS
Compute flow-based cost or conductance
#### Description

flow.dispersion computes movement conductance through a flow either, sea or wind currents. It
implements the formula described in Felícisimo et al. 2008:
Usage
cost.FMGS(wind.direction, wind.speed, target, type = "active")
flow.dispersion(x, fun = cost.FMGS, output = "transitionLayer", ...)
Arguments
wind.direction A vector or skalar containing wind directions.
wind.speed A vector or skalar containing wind speeds.
target direction of the target cell
type Could be either "passive" or "active".In "passive" mode, movement against flow
direction is not allowed (deviations from the wind direction higher than 90). In
"active" mode, the movement can go against flow direction, by increasing the
cost.
x RasterStack object with layers obtained from wind2raster function ("rWind"
package) with direction and speed flow values.
fun A function to compute the cost to move between cells. The default is cost.FMGS
from Felicísimo et al. (2008), see details.
output This argument allows to select diferent kinds of output. "raw" mode creates a
matrix (class "dgCMatrix") with transition costs between all cells in the raster.
"transitionLayer" creates a TransitionLayer object with conductance values to
be used with "gdistance" package.
... Further arguments passed to or from other methods.
#### Details 
 
Cost=(1/Speed)*(HorizontalFactor)
being HorizontalFactor a "function that incrementaly penalized angular deviations from the wind
direction" (Felicísimo et al. 2008).
#### Value

In "transitionLayer" output, the function returns conductance values (1/cost)to move betwen all cells
in a raster having into account flow speed and direction obtained from wind.fit function("rWind"
package). As wind or sea currents implies directionality, flow.dispersion produces an anisotropictidy
5
conductance matrix (asimetric). Conductance values are used later to built a TransitionLayer object
from "gdistance" package.
In "raw" output, flow.dispersion creates a sparse Matrix with cost values.
Note
Note that for large data sets, it could take a while. For large study areas is strongly adviced perform
the analysis in a remote computer or a cluster.

#### Author(s) 
 
Javier Fernández-López; Klaus Schliep

#### References 
 
Felicísimo, Á. M., Muñoz, J., & González-Solis, J. (2008). Ocean surface winds drive dynamics of
transoceanic aerial movements. PLoS One, 3(8), e2928.
Jacob van Etten (2017). R Package gdistance: Distances and Routes on Geographical Grids. Journal
of Statistical Software, 76(13), 1-21. doi:10.18637/jss.v076.i13
See Also
wind.dl, wind2raster
#### Examples
 ```{r}
require(gdistance)
data(wind.data)
wind <- wind2raster(wind.data)
Conductance<-flow.dispersion(wind, type="passive")
transitionMatrix(Conductance)
image(transitionMatrix(Conductance))
