fbpRaster
Raster-based Fire Behavior Prediction System Calculations
Description
fbpRaster calculates the outputs from the Canadian Forest Fire Behavior Prediction (FBP) System
(Forestry Canada Fire Danger Group 1992) based on raster format fire weather and fuel moisture
conditions (from the Canadian Forest Fire Weather Index (FWI) System (Van Wagner 1987)), fuel
type, date, and slope. Fire weather, for the purpose of FBP System calculation, comprises obser-
vations of 10 m wind speed and direction at the time of the fire, and two associated outputs from
the Fire Weather Index System, the Fine Fuel Moisture Content (FFMC) and Buildup Index (BUI).
Raster-based FWI System components can be calculated with the sister function fwiRaster.
Usage
fbpRaster(input,output="Primary",select=NULL,m=NULL,cores=1)12
fbpRaster
Arguments
input
The input data, a RasterStack containing fuel types, fire weather component,
and slope layers (see below). Each vector of inputs defines a single FBP System
prediction for a single fuel type and set of weather conditions. The RasterStack
can be used to evaluate the FBP System for a single fuel type and instant in time,
or multiple records for a single point (e.g., one weather station, either hourly or
daily for instance) or multiple points (multiple weather stations or a gridded
surface). All input variables have to be named as listed below, but they are case
insensitive, and do not have to be in any particular order. Fuel type is of type
character; other arguments are numeric. Missing values in numeric variables
could either be assigned as NA or leave as blank.
Required Inputs:
Input
FuelType Description/Full name
FBP System Fuel Type including "C-1", "C-2", "C-3", "C-4", "C-5","C2" "C-6", "C-7", "D-1", "M-1", "M-2", "M-
LAT
LONG
FFMC
BUI
WS
GS
Dj
Aspect Fuel Type code
C-1 1
C-2 2
C-3 3
C-4 4
C-5 5
C-6 6
C-7 7
D-1 8
M-1 9
M-2 10
M-3 11
M-4 12
NF 13
O-1a 14
O-1b 15
S-1 16
S-2 17
S-3 18
WA 19
Latitude [decimal degrees]
Longitude [decimal degrees]
Fine fuel moisture code [FWI System component]
Buildup index [FWI System component]
Wind speed [km/h]
Ground Slope [percent]
Julian day
Aspect of the slope [decimal degrees]
Optional Inputs (1): Variables associated with certain fuel types. These couldfbpRaster
13
be skipped
if relevant fuel types do not appear in the input data.
Input
PC
PDF
cc
GFL
Full names of inputs
Percent Conifer for M1/M2 [percent]
Percent Dead Fir for M3/M4 [percent]
Percent Cured for O1a/O1b [percent]
Grass Fuel Load [kg/m^2]
Defaults
50
35
80
0.35
Optional Inputs (2): Variables that could be ignored without causing major im-
pacts to the
primary outputs
Input
CBH
WD
Accel
ELV*
BUIEff
D0
hr
ISI
CFL
FMC
SH
SD
theta
output
Full names of inputs
Crown to Base Height [m]
Wind direction [decimal degrees]
Acceleration: 1 = point, 0 = line
Elevation [meters above sea level]
Buildup Index effect: 1=yes, 0=no
Julian day of minimum Foliar Moisture Content
Hours since ignition
Initial spread index
Crown Fuel Load [kg/m^2]
Foliar Moisture Content if known [percent]
C-6 Fuel Type Stand Height [m]
C-6 Fuel Type Stand Density [stems/ha]
Elliptical direction of calculation [degrees]
Defaults
3
0
0
NA
1
0
1
0
1.0
0
0
0
0
FBP output offers 3 options (see details in Values section):
Outputs
Primary (default)
Secondary
All
Number of outputs
8
34
42
select Selected outputs
m m Optimal number of pixels at each iteration of computation when ncell(input) >= 1000.
Default m = NULL, where the function will assign m = 1000 when ncell(input)
is between 1000 and 500,000, and m=3000 otherwise. By including this option,
the function is able to process large dataset more efficiently. The optimal value
may vary with different computers.
cores Number of CPU cores (integer) used in the computation, default is 1. By signing
cores > 1, the function will apply parallel computation technique provided by14
fbpRaster
the foreach package, which significantly reduces the computation time for large
input data (over a million grid points). For small dataset, cores=1 is actually
faster.
* Elevation is only used in the calculation of Foliar Moisture Content (FMC).
However, FMC can also be calculated without elevation input. The default is to
not use elevation in the calculation of FMC.
Details
The Canadian Forest Fire Behavior Prediction (FBP) System (Forestry Canada Fire Danger Group
1992) is a subsystem of the Canadian Forest Fire Danger Rating System, which also includes the
Canadian Forest Fire Weather Index (FWI) System. The FBP System provides quantitative esti-
mates of head fire spread rate, fuel consumption, fire intensity, and a basic fire description (e.g.,
surface, crown) for 16 different important forest and rangeland types across Canada. Using a sim-
ple conceptual model of the growth of a point ignition as an ellipse through uniform fuels and under
uniform weather conditions, the system gives, as a set of secondary outputs, estimates of flank and
back fire behavior and consequently fire area perimeter length and growth rate.
The FBP System evolved since the mid-1970s from a series of regionally developed burning indexes
to an interim edition of the nationally develop FBP system issued in 1984. Fire behavior models for
spread rate and fuel consumption were derived from a database of over 400 experimental, wild and
prescribed fire observations. The FBP System, while providing quantitative predictions of expected
fire behavior is intended to supplement the experience and judgment of operational fire managers
(Hirsch 1996).
The FBP System was updated with some minor corrections and revisions in 2009 (Wotton et al.
2009) with several additional equations that were initially not included in the system. This fbp
function included these updates and corrections to the original equations and provides a complete
suite of fire behavior prediction variables. Default values of optional input variables provide a
reasonable mid-range setting. Latitude, longitude, elevation, and the date are used to calculate foliar
moisture content, using a set of models defined in the FBP System; note that this latitude/longitude-
based function is only valid for Canada. If the Foliar Moisture Content (FMC) is specified directly
as an input, the fbp function will use this value directly rather than calculate it. This is also true of
other input variables.
Note that Wind Direction (WD) is the compass direction from which wind is coming. Wind azimuth
(not an input) is the direction the wind is blowing to and is 180 degrees from wind direction; in the
absence of slope, the wind azimuth is coincident with the direction the head fire will travel (the
spread direction azimuth, RAZ). Slope aspect is the main compass direction the slope is facing.
Slope azimuth (not an input) is the direction a head fire will spread up slope (in the absence of
wind effects) and is 180 degrees from slope aspect (Aspect). Wind direction and slope aspect are
the commonly used directional identifiers when specifying wind and slope orientation respectively.
The input theta specifies an angle (given as a compass bearing) at which a user is interested in
fire behavior predictions; it is typically some angle off of the final spread rate direction since if
for instance theta=RAZ (the final spread azimuth of the fire) then the rate of spread at angle theta
(TROS) will be equivalent to ROS.
Value
fbpRaster returns a RasterStack with primary, secondary, or all output variables, a combination of
the primary and secondary outputs. Primary FBP output includes the following 8 raster layers:fbpRaster
15
CFB Crown Fraction Burned by the head fire
CFC Crown Fuel Consumption [kg/m^2]
FD Fire description (1=Surface, 2=Intermittent, 3=Crown)
HFI Head Fire Intensity [kW/m]
RAZ Spread direction azimuth [degrees]
ROS Equilibrium Head Fire Rate of Spread [m/min]
SFC Surface Fuel Consumption [kg/m^2]
TFC Total Fuel Consumption [kg/m^2]
Secondary FBP System outputs include the following 34 raster layers. In order to calculate the
reliable secondary outputs, depending on the outputs, optional inputs may have to be provided.
BE BUI effect on spread rate
SF Slope Factor (multiplier for ROS increase upslope)
ISI Initial Spread Index
FFMC Fine fuel moisture code [FWI System component]
FMC Foliar Moisture Content [%]
Do Julian Date of minimum FMC
RSO Critical spread rate for crowning [m/min]
CSI Critical Surface Intensity for crowning [kW/m]
FROS Equilibrium Flank Fire Rate of Spread [m/min]
BROS Equilibrium Back Fire Rate of Spread [m/min]
HROSt Head Fire Rate of Spread at time hr [m/min]
FROSt Flank Fire Rate of Spread at time hr [m/min]
BROSt Back Fire Rate of Spread at time hr [m/min]
FCFB Flank Fire Crown Fraction Burned
BCFB Back Fire Crown Fraction Burned
FFI Equilibrium Spread Flank Fire Intensity [kW/m]
BFI Equilibrium Spread Back Fire Intensity [kW/m]
FTFC Flank Fire Total Fuel Consumption [kg/m^2]
BTFC Back Fire Total Fuel Consumption [kg/m^2]
DH Head Fire Spread Distance after time hr [m]
DB Back Fire Spread Distance after time hr [m]
DF Flank Fire Spread Distance after time hr [m]
TI Time to Crown Fire Initiation [hrs since ignition]
FTI Time to Flank Fire Crown initiation [hrs since ignition]
BTI Time to Back Fire Crown initiation [hrs since ignition]
LB Length to Breadth ratio
LBt Length to Breadth ratio after elapsed time hr16
fbpRaster
WSV Net vectored wind speed [km/hr]
TROS* Equilibrium Rate of Spread at bearing theta [m/min]
TROSt* Rate of Spread at bearing theta at time t [m/min]
TCFB* Crown Fraction Burned at bearing theta
TFI* Fire Intensity at bearing theta [kW/m]
TTFC* Total Fuel Consumption at bearing theta [kg/m^2]
TTI* Time to Crown Fire initiation at bearing theta [hrs since ignition]
*These outputs represent fire behaviour at a point on the perimeter of an elliptical fire defined by a
user input angle theta. theta represents the bearing of a line running between the fire ignition point
and a point on the perimeter of the fire. It is important to note that in this formulation the theta
is a bearing and does not represent the angle from the semi-major axis (spread direction) of the
ellipse. This formulation is similar but not identical to methods presented in Wotton et al (2009)
and Tymstra et al (2009).
Author(s)
Xianli Wang, Alan Cantin, Marc-André Parisien, Mike Wotton, Kerry Anderson, and Mike Flanni-
gan
References
1. Hirsch K.G. 1996. Canadian Forest Fire Behavior Prediction (FBP) System: user’s guide. Nat.
Resour. Can., Can. For. Serv., Northwest Reg., North. For. Cent., Edmonton, Alberta. Spec. Rep.
7. 122p.
2. Forestry Canada Fire Danger Group. 1992. Development and structure of the Canadian Forest
Fire Behavior Prediction System. Forestry Canada, Ottawa, Ontario Information Report ST-X-3.
63 p. http://cfs.nrcan.gc.ca/pubwarehouse/pdfs/10068.pdf
3. Wotton, B.M., Alexander, M.E., Taylor, S.W. 2009. Updates and revisions to the 1992 Canadian
forest fire behavior prediction system. Nat. Resour. Can., Can. For. Serv., Great Lakes For. Cent.,
Sault Ste. Marie, Ontario, Canada. Information Report GLC-X-10, 45p. http://publications.
gc.ca/collections/collection_2010/nrcan/Fo123-2-10-2009-eng.pdf
4. Tymstra, C., Bryce, R.W., Wotton, B.M., Armitage, O.B. 2009. Development and structure of
Prometheus: the Canadian wildland fire growth simulation Model. Nat. Resour. Can., Can. For.
Serv., North. For. Cent., Edmonton, AB. Inf. Rep. NOR-X-417.
See Also
fbp, fwiRaster, hffmcRaster
Examples
# The dataset is the standard test data for FBP system
# provided by Wotton et al (2009), and randomly assigned
# to a stack of raster layers
test_fbpRastersrc <- system.file("extdata", "test_fbpRaster.tif", package="cffdrs")
test_fbpRaster <- stack(test_fbpRastersrc)fireSeason
17
input<-test_fbpRaster
# Stack doesn't hold the raster layer names, we have to assign
# them:
names(input)<-c("FuelType","LAT","LONG","ELV","FFMC","BUI", "WS","WD","GS","Dj","D0","hr","PC",
"PDF","GFL","cc","theta","Accel","Aspect","BUIEff","CBH","CFL","ISI")
# Primary outputs:
system.time(foo<-fbpRaster(input = input))
# Using the "select" option:
system.time(foo<-fbpRaster(input = input,select=c("HFI","TFC", "ROS")))
# Secondary outputs:
system.time(foo<-fbpRaster(input = input,output="S"))
# All outputs:
#system.time(foo<-fbpRaster(input = input,output="A"))
### Additional, longer running examples are commented out below ###
# Keep only the required input layers, the other layers would be
# assigned with default values:
# keep only the required inputs:
# dat0<-input[[c("FuelType","LAT","LONG","FFMC","BUI","WS","GS", "Dj","Aspect")]]
# system.time(foo<-fbpRaster(input = dat0,output="A"))
#
#
#
#
#
#
#
#
#
#
Using parallel computation option. This works better only when
the input is large.
First, create a large input by expanding the input stack:
s<-input
nrow(s)<-1000
ncol(s)<-1000
s<-resample(input,s,method='ngb')
Compare whether assign multiple cores would save running time:
system.time(foo1<-fbpRaster(s))
system.time(foo2<-fbpRaster(s,cores=4))
fireSeason
Fire Season Start and End
Description
fireSeason calculates the start and end fire season dates for a given weather station. The current
method used in the function is based on three consecutive daily maximum temperature thresholds
(Wotton and Flannigan 1993, Lawson and Armitage 2008). This function process input from a
single weather station.
Usage
fireSeason(input,fs.start=12,fs.end=5,method="WF93", consistent.snow=FALSE)
Arguments
input
A data.frame containing input variables of including the date/time and daily
maximum temperature. Variable names have to be the same as in the following18
fireSeason
list, but they are case insensitive. The order in which the input variables are
entered is not important either.
yr
mon
day
tmax
snow_depth
(required)
(required)
(required)
(required)
(optional)
Year of the observations
Month of the observations
Day of the observations
Maximum Daily Temperature (degrees C)
Is consistent snow data in the input?
fs.start Temperature threshold (degrees C) to start the fire season (default=12)
fs.end Temperature threshold (degrees C) to end the fire season (default=5)
method
Method of fire season calculation. Options are "wf93"" or "la08" (default=WF93)
consistent.snow
Is consistent snow data in the input? (default=FALSE)
Details
An important aspect to consider when calculating Fire Weather Index (FWI) System variables is
a definition of the fire season start and end dates (Lawson and Armitage 2008). If a user starts
calculations on a fire season too late in the year, the FWI System variables may take too long to
reach equilibrium, thus throwing off the resulting indices. This function presents two method of
calculating these start and end dates, adapted from Wotton and Flannigan (1993), and Lawson and
Armitage (2008). The approach taken in this function starts the fire season after three days of max-
imum temperature greater than 12 degrees Celsius. The end of the fire season is determined after
three consecutive days of maximum temperature less than 5 degrees Celsius. The two temperature
thresholds can be adjusted as parameters in the function call.
This fire season length definition can also feed in to the overwinter DC calculations (wDC). View
the cffdrs package help files for an example of using the fireSeason, wDC, and fwi functions in
conjunction.
Value
fireSeason returns a data frame of season and start and end dates. Columns in data frame are
described below.
Primary FBP output includes the following 8 variables:
yr Year of the fire season start/end date
mon Month of the fire season start/end date
day Day of the fire season start/end date
fsdatetype Fire season date type (values are either "start" or "end")
Author(s)
Alan Cantin, Xianli Wang, Mike Wotton, and Mike FlanniganfireSeason
19
References
Wotton, B.M. and Flannigan, M.D. (1993). Length of the fire season in a changing climate. Forestry
Chronicle, 69, 187-192. http://www.ualberta.ca/~flanniga/publications/1993_Wotton_
Flannigan.pdf
Lawson, B.D. and O.B. Armitage. 2008. Weather guide for the Canadian Forest Fire Danger
Rating System. Nat. Resour. Can., Can. For. Serv., North. For. Cent., Edmonton, AB http:
//cfs.nrcan.gc.ca/pubwarehouse/pdfs/29152.pdf
See Also
fwi, wDC
Examples
library(cffdrs)
#The standard test data:
data("test_wDC")
print(head(test_wDC))
## Sort the data:
input <- with(test_wDC, test_wDC[order(id,yr,mon,day),])
#Using the default fire season start and end temperature
#thresholds:
a_fs <- fireSeason(input[input$id==1,])
#Check the result:
a_fs
#
#1
#2
#3
#4
#5
#6
#7
#8
yr mon day fsdatetype
1999
5
4
start
1999
5 12
end
1999
5 18
start
1999
5 25
end
1999
5 30
start
1999 10
6
end
2000
6 27
start
2000 10
7
end
#In the resulting data frame, the fire season starts
#and ends multiple times in the first year. It is up to the user #for how to interpret this.
#modified fire season start and end temperature thresholds
a_fs <- fireSeason (input[input$id==1,],fs.start=10, fs.end=3)
a_fs
#
yr mon day fsdatetype
#1 1999
5
2
start
#2 1999 10 20
end
#3 2000
6 16
start
#4 2000 10
7
end
#select another id value, specify method explicitly
b_fs <- fireSeason(input[input$id==2,],method="WF93")20
fwi
#print the calculated fireseason
b_fs
# yr mon day fsdatetype
#1 1980
4 21
start
#2 1980
9 19
end
#3 1980 10
6
start
#4 1980 10 16
end
#5 1981
5 21
start
#6 1981 10 13
end

