gfmc
Grass Fuel Moisture Code
Description
gfmc calculates both the moisture content of the surface of a fully cured matted grass layer and also
an equivalent Grass Fuel Moisture Code (gfmc) (Wotton, 2009) to create a parallel with the hourly
ffmc (see the fwi and hffmcfunctions). The calculation is based on hourly (or sub-hourly) weather
observations of temperature, relative humidity, wind speed, rainfall, and solar radiation. The user
must also estimate an initial value of the gfmc for the layer. This function could be used for either
one weather station or multiple weather stations.
Usage
gfmc(input, GFMCold=85,batch=TRUE,time.step=1,roFL=0.3, out="GFMCandMC")
Arguments
input
A dataframe containing input variables of daily noon weather observations.
Variable names have to be the same as in the following list, but they are case
insensitive. The order in which the input variables are entered is not important.
temp
rh
ws
prec
isol
(required)
(required)
(required)
(required)
(required)
Temperature (centigrade)
Relative humidity (%)
10-m height wind speed (km/h)
1-hour rainfall (mm)
Solar radiation (kW/m^2)28
gfmc
mon
day
GFMCold
time.step
roFL
batch
out
(recommended)
(optional)
Month of the year (integer 1-12)
Day of the month (integer)
Previous value of GFMC (i.e. value calculated at the previous time step)[default
is 85 (which corresponds to a moisture content of about 16%)]. On the first cal-
culation this is the estimate of the GFMC value at the start of the time step. The
GFMCold argument can accept a single initial value for multiple weather stations,
and also accept a vector of initial values for multiple weather stations. NOTE:
this input represents the CODE value, not a direct moisture content value. The
CODE values in the Canadian FWI System increase within decreasing moisture
content. To roughly convert a moisture content value to a CODE value on the
FF-scale (used in the FWI Systems FFMC) use GFMCold =101-gmc (where gmc
is moisture content in %)
Time step (hour) [default 1 hour]
The nominal fuel load of the fine fuel layer, default is 0.3 kg/m^2
Whether the computation is iterative or single step, default is TRUE. When
batch=TRUE, the function will calculate hourly or sub-hourly GFMC for one
weather station over a period of time iteratively. If multiple weather stations
are processed, an additional "id" column is required in the input to label dif-
ferent stations, and the data needs to be sorted by time sequence and "id". If
batch=FALSE, the function calculates only one time step (1 hour) base on either
the previous hourly GFMC or the initial start value.
Output format, default is "GFMCandMC", which contains both GFMC and
moisture content (MC) in a data.frame format. Other choices include: "GFMC",
"MC", and "ALL", which include both the input and GFMC and MC.
Details
The Canadian Forest Fire Danger Rating System (CFFDRS) is used throughout Canada, and in
a number of countries throughout the world, for estimating fire potential in wildland fuels. This
new Grass Fuel Moisture Code (GFMC) is an addition (Wotton 2009) to the CFFDRS and retains
the structure of that System’s hourly Fine Fuel Moisture Code (HFFMC) (Van Wagner 1977). It
tracks moisture content in the top 5 cm of a fully-cured and fully-matted layer of grass and thus is
representative of typical after winter conditions in areas that receive snowfall. This new moisture
calculation method outputs both the actual moisture content of the layer and also the transformed
moisture Code value using the FFMC’s FF-scale. In the CFFDRS the moisture codes are in fact
relatively simple transformations of actual moisture content such that decreasing moisture content
(increasing dryness) is indicated by an increasing Code value. This moisture calculation uses the
same input weather observations as the hourly FFMC, but also requires an estimate of solar radiation
incident on the fuel.
Value
gfmc returns GFMC and moisture content (MC) values collectively (default) or separately.
Author(s)
Xianli Wang, Mike Wotton, Alan Cantin, and Mike Flannigangfmc
29
References
Wotton, B.M. 2009. A grass moisture model for the Canadian Forest Fire Danger Rating System.
In: Proceedings 8th Fire and Forest Meteorology Symposium, Kalispell, MT Oct 13-15, 2009.
Paper 3-2. https://ams.confex.com/ams/pdfpapers/155930.pdf
Van Wagner, C.E. 1977. A method of computing fine fuel moisture content throughout the diur-
nal cycle. Environment Canada, Canadian Forestry Service, Petawawa Forest Experiment Station,
Chalk River, Ontario. Information Report PS-X-69. http://cfs.nrcan.gc.ca/pubwarehouse/
pdfs/25591.pdf
See Also
fwi, hffmc
Examples
library(cffdrs)
#load the test data
data("test_gfmc")
# show the data format:
head(test_gfmc)
#
yr mon day hr temp
rh
ws prec isol
# 1 2006
5 17 10 15.8 54.6 5.0
0 0.340
# 2 2006
5 17 11 16.3 52.9 5.0
0 0.380
# 3 2006
5 17 12 18.8 45.1 5.0
0 0.626
# 4 2006
5 17 13 20.4 40.8 9.5
0 0.656
# 5 2006
5 17 14 20.1 41.7 8.7
0 0.657
# 6 2006
5 17 15 18.6 45.8 13.5
0 0.629
# (1) gfmc default:
# Re-order the data by year, month, day, and hour:
dat<-test_gfmc[with(test_gfmc,order(yr,mon,day,hr)),]
# Because the test data has 24 hours input variables
# it is possible to calculate the hourly GFMC continuously
# through multiple days(with the default initial GFMCold=85):
dat$gfmc_default<-gfmc(dat)
# two variables will be added to the input, GFMC and MC
head(dat)
# (2) For multiple weather stations:
# One time step (1 hour) with default initial value:
foo<-gfmc(dat,batch=FALSE)
# Chronical hourly GFMC with only one initial
# value (GFMCold=85), but multiple weather stations.
# Note: data is ordered by date/time and the station id. Subset
# the data by keeping only the first 10 hours of observations
# each day:
dat1<-subset(dat,hr%in%c(0:9))
#assuming observations were from the same day but with
#9 different weather stations:
dat1$day<-NULL
dat1<-dat1[with(dat1,order(yr,mon,hr)),]
dat1$id<-rep(1:8,nrow(dat1)/8)
#check the data:30
hffmc
head(dat1)
# Calculate GFMC for multiple stations:
dat1$gfmc01<-gfmc(dat1,batch=TRUE)
# We can provide multiple initial GFMC (GFMCold) as a vector:
dat1$gfmc02<- gfmc(dat1,GFMCold = sample(70:100,8, replace=TRUE),batch=TRUE)
# (3)output argument
## include all inputs and outputs:
dat0<-dat[with(dat,order(yr,mon,day,hr)),]
foo<-gfmc(dat,out="ALL")
## subhourly time step:
gfmc(dat0,time.step=1.5)
hffmc
Hourly Fine Fuel Moisture Code
Description
hffmc is used to calculate hourly Fine Fuel Moisture Code (FFMC) and is based on a calculation
routine first described in detail by Van Wagner (1977) and which has been updated in minor ways by
the Canadian Forest Service to have it agree with the calculation methodology for the daily FFMC
(see fwi). In its simplest typical use this current routine calculates a value of FFMC based on a
series of uninterrupted hourly weather observations of screen level (~1.4 m) temperature, relative
humidity, 10 m wind speed, and 1-hour rainfall. This implementation of the function includes an
optional time.step input which is defaulted to one hour, but can be reduced if sub-hourly calculation
of the code is needed. The FFMC is in essence a bookkeeping system for moisture content and thus
it needs to use the last time.step’s value of FFMC in its calculation as well. This function could be
used for either one weather station or for multiple weather stations.
Usage
hffmc(weatherstream,ffmc_old=85,time.step=1,calc.step=FALSE,batch=TRUE,hourlyFWI=FALSE)
Arguments
weatherstream
temp
rh
ws
prec
hr
bui
(required)
(required)
(required)
(required)
(optional)
(optional)
A dataframe containing input variables of hourly weather observations. It is
important that variable names have to be the same as in the following list, but
they are case insensitive. The order in which the input variables are entered is
not important.
Temperature (centigrade)
Relative humidity (%)
10-m height wind speed (km/h)
1-hour rainfall (mm)
Hourly value to calculate sub-hourly ffmc
Daily BUI value for the computation of hourly FWI. It is required when hourlyFWI=TRUE.
Typically this dataframe also contains date and hour fields so outputs can behffmc
31
associated with a specific day and time, however these fields are not used in
the calculations. If multiple weather stations are being used, a weather station
ID field is typically included as well, though this is simply for bookkeeping
purposes and does not affect the calculation.
ffmc_old Initial FFMC. At the start of calculations at a particular station there is a need
to provide an estimate of the FFMC in the previous timestep; this is because the
FFMC is, in essence, a bookkeeping system for moisture. If no estimate of previ-
ous hour’s FFMC is available the function will use default value, ffmc_old=85.
When using the routine to calculate hourly FFMC at multiple stations the ffmc_old
argument can also accept a vector with the same number of weather stations.
time.step Is the time (in hours) between the previous value of FFMC and the current time
at which we want to calculate a new value of the FFMC. When not specified it
will take on a default value of time.step=1.
calc.step Optional for whether time step between two observations is calculated. Default
is FALSE, no calculations. This is used when time intervals are not uniform in
the input.
batch Whether the computation is iterative or single step, default is TRUE. When
batch=TRUE, the function will calculate hourly or sub-hourly FFMC for one
weather station over a period of time iteratively. If multiple weather stations are
processed, an additional "id" column is required in the input weatherstream to
label different stations, and the data needs to be sorted by date/time and "id".
If batch=FALSE, the function calculates only one time step base on either the
previous hourly FFMC or the initial start value.
hourlyFWI Optional for the computation of hourly ISI, FWI, and DSR. Default is FALSE.
While hourlyFWI=TRUE, daily BUI is required for the computation of FWI.
Details
The hourly FFMC is very similar in its structure and calculation to the Canadian Forest Fire Weather
Index System’s daily FFMC (fwi) but has an altered drying and wetting rate which more realisti-
cally reflects the drying and wetting of a pine needle litter layer sitting on a decaying organic layer.
This particular implementation of the Canadian Forest Fire Danger Rating System’s hourly FFMC
provides for a flexible time step; that is, the data need not necessarily be in time increments of
one hour. This flexibility has been added for some users who use this method with data sampled
more frequently that one hour. We do not recommend using a time step much greater than one
hour. An important and implicit assumption in this calculation is that the input weather is constant
over the time step of each calculation (e.g., typically over the previous hour). This is a reasonable
assumption for an hour; however it can become problematic for longer periods. For brevity we have
referred to this routine throughout this description as the hourly FFMC.
Because of the shortened time step, which can lead to more frequent calculations and conversion
between moisture content and the code value itself, we have increased the precision of one of the
constants in the simple formula that converts litter moisture content to the ’Code’ value. This is
necessary to avoid a potential bias that gets introduced during extremely dry conditions. This is
simply a change in the precision at which this constant is used in the equation and is not a change
to the standard FFMC conversion between moisture and code value (which is referred to as the
FF-scale).32
hffmc
The calculation requires the previous hour’s FFMC as an input to the calculation of the current
hour’s FFMC; this is because the routine can be thought of as a bookkeeping system and needs to
know the amount of moisture being held in the fuel prior to any drying or wetting in the current
period. After each hour’s calculation that newly calculated FFMC simply becomes the starting
FFMC in the next hour’s calculation. At the beginning of the calculations at a station this previous
hours FFMC must be estimated. It is typical to use a value of 85 when this value cannot be estimated
more accurately; this code value corresponds to a moisture content of about 16% in typical pine litter
fuels.
Value
hffmc returns a vector of hourly or sub-hourly FFMC values, which may contain 1 or multiple
elements. Optionally when hourlyFWI=TRUE, the function also output a data.frame contains input
weatherstream as well as the hourly or sub-hourly FFMC, ISI, FWI, and DSR.
Author(s)
Xianli Wang, Mike Wotton, Alan Cantin, Brett Moore, and Mike Flannigan
References
Van Wagner, C.E. 1977. A method of computing fine fuel moisture content throughout the diur-
nal cycle. Environment Canada, Canadian Forestry Service, Petawawa Forest Experiment Station,
Chalk River, Ontario. Information Report PS-X-69. http://cfs.nrcan.gc.ca/pubwarehouse/
pdfs/25591.pdf
See Also
fbp, fwi, hffmcRaster
Examples
library(cffdrs)
data("test_hffmc")
# show the data format:
head(test_hffmc)
# (1)hffmc default:
# Re-order the data by year, month, day, and hour:
test_hffmc<-test_hffmc[with(test_hffmc, order(yr,mon,day,hr)),]
# Because the test data has 24 hours input variables
# it is possible to calculate the hourly FFMC chronically
# through multiple days(with the default initial ffmc_old=85):
test_hffmc$ffmc_default<-hffmc(test_hffmc)
# (2) Calculate FFMC for multiple stations:
# Calculate hourly FFMC with only one initial
# value (ffmc_old=85), but multiple weather stations.
# Sort the input by date/time and the station id:
test_hffmc<-test_hffmc[with(test_hffmc,order(yr,mon,hr)),]
# Add weather station id:
test_hffmc$id<-rep(1:10,nrow(test_hffmc)/10)
#check the data:hffmcRaster
33
head(test_hffmc)
test_hffmc$ffmc01<-hffmc(test_hffmc,batch=TRUE)
# With multiple initial FFMC (ffmc_old) as a vector:
test_hffmc$ffmc02<- hffmc(test_hffmc,ffmc_old = sample(70:100,10, replace=TRUE),batch=TRUE)
# One time step assuming all records are from different
# weather stations:
foo<-hffmc(test_hffmc,batch=FALSE)
# (3) output all hourly FWI System variables:
test_hffmc$id<-NULL
test_hffmc<-test_hffmc[with(test_hffmc,
order(yr,mon,day,hr)),]
foo<-hffmc(test_hffmc,hourlyFWI=TRUE)
# this will not run: warning message requesting for daily BUI
test_hffmc$bui<-100
foo<-hffmc(test_hffmc,hourlyFWI=TRUE)
# (4) Calculate time steps in case the time intervals are
# not uniform:
dat0<-test_hffmc[sample(1:30,20),]
dat0<-dat0[with(dat0,order(yr,mon,day,hr)),]
# with or without calc.step, hffmc is going to generate
# different FFMC values.
# without calculating time step (default):
hffmc(dat0,time.step=1)
# with calc.step=TRUE, time.step=1 is applied to
# only the first record, the rests would be calculated:
hffmc(dat0,time.step=1,calc.step=TRUE)
