
#### Description 

LIDAR scan dataset in BBCH 65 (grapevine).Where x is width, y is height and z is front view or
path of the tractor.10
LIDAR_data

#### Usage 

data(LIDAR_data)

#### Format 

A data frame with 10108 observations on the following 3 variables.
V1 a numeric vector that represents x value or width
V2 a numeric vector that represents y value or height
V3 a numeric vector that represents z value or front view

#### Details 

The laser scanner used was a LMS-200 model (Sick,Dusseldorf,Germany), a fully-automatic diver-
gent laser scanner based on the measurement of time-of-flight (TOF) with an accurancy of 15 mm
in a single shoot measurement and 5 mm standard deviation in a range upto 8m. The time between
the transmission and the reception of the pulsed near-infrared laser beam is used to measure the
distance between the scanner and the reflecting object surface. The laser beam is deflected by a
rotating mirror turning at 4500 rpm, which results in a fan shaped scan pattern where the maximum
scanning angle is 180 degree.
Source
LIDAR scan in BBCH 65 stage.

#### References 

Llorens,J.,Gil,E.,Llop,J.,Escola,A.,2011. Ultrasonic and LIDAR Sensors for Electronic Canopy
Characterization in Vineyards: Advances to Improve Pesticide Application Methods. Sensors 11,
2177-2194.

#### Examples 
<pre><code>
## LIDAR_data is the input to Extract_plant_grapevine_function.
data(LIDAR_data, package ='PROTOLIDAR')
x = LIDAR_data[,1]
y = LIDAR_data[,2]
z = LIDAR_data[,3]LWA_lidar_function
11
LWA_lidar_function
Leaf Wall Area (LWA) measured in m^2*ha^-1.
</code></pre>
#### Description 

LWA need as inputs the height of canopy (m) the ground area (generally one hectare, measured in
m^2) and the row spacing (m).

#### Usage 

LWA_lidar_function(height_canopy, ground_area, row_spacing)

#### Arguments 

* height_canopy height of canopy manually or measured with Height_canopy_function.
* ground_area is the orchard area measured in m^2, generally one hectare.
* row_spacing row spacing measured in meters.

#### Authors(s) 

Monica Fernanda Rinaldi

#### References 

Walklate, P.J., Cross, J.V., 2011. An examination of Leaf-Wall-Area dose expression. Crop Protec-
tion 35, 132-134.

#### Examples 

## Should be DIRECTLY executable !! ----
height_canopy = 2 ## this value is the maximum of Height_canopy_function.
ground_area = 10000 ## generally is one hectare in m^2.
row_spacing = 2.9 ## measured in meters.
## The function is currently defined as
function(height_canopy,ground_area,row_spacing){
LWA <- 2* height_canopy * (ground_area/row_spacing)
return(LWA)
}
LWA_lidar_function(height_canopy,ground_area,row_spacing)12
Number_lidar_points_into_canopy_function
Number_lidar_points_into_canopy_function
Number of LIDAR points into the canopy.

#### Description 

This function describe the number of points measured with LIDAR scan into the canopy.

#### Usage 

Number_lidar_points_into_canopy_function(data_3D, distance_left, distance_right, min_canopy, max_can

#### Arguments 

* ``data_3D``:  ``data_3D`` is the output from Extract_plant_grapevine_function.
* ``distance_left``:  the left distancethe left distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
* ``distance_right``:  the right distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
min_canopy the minimum height of the canopy.
max_canopy the maximum height of the canopy.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

## Should be DIRECTLY executable !! ----
## For example:
data (LIDAR_data)
x <- LIDAR_data[,1]
y <- LIDAR_data[,2]
z <- LIDAR_data[,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
z_min <- 1.1
z_max <- 1.13
y_min <- 0.4Replicate_plants_function
13
y_max <- 0.5
* ``distance_left``:  the left distance<- -0.6
distance_right <- 0.51
data_3D <- Extract_plant_3D_function(out,z_min,z_max,y_min,y_max,distance_left,distance_right)
min_canopy <- 0.4
max_canopy <- 2
## The function is currently defined as
Number_LIDAR_points_into_canopy_function <- function (data_3D,distance_left,distance_right,min_canopy,max_canop
x_plant <- y_plant <- z_plant <- NULL
canopy <- subset(data_3D, data_3D$z_plant >= * ``distance_left``:  the left distance& data_3D$z_plant <= distance_right & data_3D$y_plan
N_points <- length(canopy[,1])
return (N_points)
}
Number_LIDAR_points_into_canopy_function(data_3D,distance_left,distance_right,min_canopy,max_canopy)
Replicate_plants_function
