PRocess TOol LIdar DAta in R.

Extract_plant_grapevine_function
Extract vine plant from the entire dataset.

#### Description 

The function cut the plant at fixes values of x,y and z. Where x is width, y is height and z is front
view or path of the tractor.6
Extract_plant_grapevine_function

#### Usage 

Extract_plant_grapevine_function(x, y, z, zdistance, miny, maxy, minx, maxx, minz, maxz)

#### Arguments 

x the width of the plant measured with LIDAR scan in cm.
y the height of the plant measured with LIDAR scan in cm.
z the front of the plant or path of the tractor measured with LIDAR scan in cm.
zdistance the z distance of LIDAR scan measured in cm.
miny the minimum height at which we cut the plant measured in cm.
maxy the maximum height at which we cut the plant measured in cm.
minx the minimum width to which we want to measure the plant measured in cm.
maxx the maximum width to which we want to measure the plant measured in cm.
minz the minimum distance at which we cut the plant, measured in cm.
maxz the maximum distance at which we cut the plant, measured in cm.

#### Details 

Path or direction of the tractor at constant velocity.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

##
##
##
##
Should be DIRECTLY executable !! --
First needed the LIDAR_data scan (that is one dataframe with x,y,z columns).
Second needed define these inputs in cm: zdistance,miny,maxy,minx,maxx,minz,maxz.
For example:
data (LIDAR_data)
x <- LIDAR_data [,1]
y <- LIDAR_data [,2]
z <- LIDAR_data [,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
## The function is currently defined as
Extract_plant_grapevine_function <- function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz){
y <- -y
y <- y-min(y)
z<- (z*zdistance)/max(z)
x_cm <- 0Height_canopy_function
7
y_cm <- 0
z_cm <- 0
for (i in 1:length(x)){
if (x[i] >= minx && x[i] <= maxx && y[i] >= miny && y[i] <= maxy && z[i] >= minz && z[i] <= maxz) {
y_cm[i] <- y[i]
x_cm[i] <- x[i]
z_cm[i] <- z[i]
}
}
y_cm <- na.omit(y_cm[2:length(y_cm)])
y_cm <- as.numeric((y_cm-min(y_cm))/1000)
x_cm <- as.numeric(na.omit(x_cm[2:length(x_cm)])/1000)
z_cm <- as.numeric(na.omit(z_cm[2:length(z_cm)])/100)
return <- data.frame(x_cm,y_cm,z_cm)
}
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
x = out[,1]
y = out[,2]
z = out[,3]
# plot
par(mfcol=c(2,2))
plot(x,y,pch=20,cex=.4,xlab='Width (m)', ylab='Height (m)', main='Grapevine BBCH')
plot(x,z,pch=20,cex=.4,xlab='Width (m)', ylab='Front (m)', main='Grapevine BBCH')
plot(z,y,pch=20,cex=.4,xlab='Front (m)', ylab='Height (m)', main='Grapevine BBCH')
Height_canopy_function
Height of the canopy measured with LIDAR scan.

#### Description 

From the LIDAR dataset can be calculate the height of the grapevine plant. The function returns
the average, minimum and maximum value of the height measured in meters.

#### Usage 

Height_canopy_function(data_3D, distance_left, distance_right, min_canopy, max_canopy)

#### Arguments 

data_3D
distance_left
data_3D is the output from Extract_plant_3D_function.
the left distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
* ``distance_right``:  the right distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
min_canopy
the minimum height of the canopy, measured in meters.
max_canopy
the maximum height of the canopy, measured in meters.8
LAI_function

#### Details 

Maximum and minimum values of height of canopy could be approximative values.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

## Should be DIRECTLY executable !! ----
## Data_3D is the output from the Extrac_plant_3D_function.
## For example:
data (LIDAR_data)
x <- LIDAR_data[,1]
y <- LIDAR_data[,2]
z <- LIDAR_data[,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
z_min <- 1.1
z_max <- 1.13
y_min <- 0.4
y_max <- 0.5
* ``distance_left``:  the left distance<- -0.6
distance_right <- 0.51
data_3D <- Extract_plant_3D_function(out,z_min,z_max,y_min,y_max,distance_left,distance_right)
min_canopy <- 0.4 # is the minimum height of the canopy, approximately . Measured in meters.
max_canopy <- 2 # is the maximum height of the canopy, approximately . Measured in meters.
## The function is currently defined as
Height_canopy_function <- function(data_3D,distance_left,distance_right,min_canopy,max_canopy){
x_plant <- y_plant <- z_plant <- NULL
canopy <- subset(data_3D, data_3D$z_plant >= * ``distance_left``:  the left distance& data_3D$z_plant <= distance_right & data_3D$y_plan
mean_height_canopy <- mean(canopy[,2])
min_height_canopy <- min(canopy[,2])
max_height_canopy <- max(canopy[,2])
return(data.frame(mean_height_canopy,min_height_canopy,max_height_canopy))
}
height_canopy <- Height_canopy_function(data_3D,distance_left,distance_right,min_canopy,max_canopy)[,1]
LAI_function
Leaf Area Index (LAI) calculate from LIDAR scan.LIDAR_data
9

#### Description 

The LAI need in inputs the number of leaves, the leaf area (m^2),row distance (m) and in row
spacing (m).

#### Usage 

LAI_function(Number_of_leaves_by_plant, Leaf_Area, row_distance, in_row_distance)

#### Arguments 

Number_of_leaves_by_plant
here need count the number of leaves of the plant.
Leaf_Area
here need calculate the leaf area, measured in m^2.
row_distance
the row distance of the orchard measured in meters.
in_row_distance
the in row distance or distance between plants of the orchard measured in meters.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

## Should be DIRECTLY executable !! ----
## Here needed some inputs measured manually like leaf area (m^2) and number of leaves.
number_of_leaves <- 420
leaf_area <- 0.010 ## measured in m^2.
row_distance <- 2.9 ## measured in meters.
in_row_distance <- 1.4 ## measured in meters.
## The function is currently defined as
LAI_function <- function(Number_of_leaves_by_plant,Leaf_Area,in_row_distance){
LAI <- Number_of_leaves_by_plant * Leaf_Area / in_row_distance
return(LAI)
}
LAI_function(number_of_leaves,leaf_area,in_row_distance)
LIDAR_data
