
#### Description 

PROTOLIDAR package contains functions for analyze the LIDAR scan of plants (grapevine) and
make with the outputs 3D maps in GRASS-GIS.

#### Details 

Package:
Type:
Version:
Date:
License:
LazyLoad:
PROTOLIDAR
Package
1.0
2012-12-14
GPL(>=2)
yes
This package help to analyze the LIDAR scan and extract the grapevine plant for see the plant in
3D GRASS GIS maps.
The package contains the following dataset and functions:
LIDAR_data is the dataset of the LIDAR scan. Represent the grapevine plant (BBCH 65).
Extract_plant_grapevine_function: which cuts the excess data.
Extract_plant_3D_function: helps to position the axis in the center of the plant.
Height_canopy_function: to measure the height of canopy from the LIDAR scan.
Width_canopy_function:to measure the width of canopy from the LIDAR scan.
Number_LIDAR_points_function: to calculate the number of points into the canopy.
LAI_function: to calculate the leaf area index.
LWA_lidar_function:to calculate the leaf wall area.
TRV_lidar_function: to calculate tree row volume in m^3*ha^-1.
Rotate_function: to rotate plants to match with the planting line.
Replicate_plants_function: to replicate plants.

#### Authors(s) 

Monica Fernanda Rinaldi<monica.rinaldi@gmail.com>
Emilio Gil<emilio.gil@upc.edu>
Jordi Llorens<jordi.llorens.calveras@upc.edu>
Maintainer: Monica Fernanda Rinaldi<monica.rinaldi@gmail.com>PROTOLIDAR-package
3

#### References 

Rinaldi, M. F.,2012. Modelling the impact of climate change on the Interaction between host and
pest/pathogen phenologies at regional level: Trentino - Italy. Unpublished PhD diss. Doctoral
School on the Agro-food System - Agrisystem - Cycle XXIV - Universita Cattolica del Sacro Cuore
-UNICATT - Piacenza- Italy.
See Also
PROTOLIDAR-package

#### Examples 

## Should be DIRECTLY executable !!
## For example:
data (LIDAR_data)
x <- LIDAR_data [,1]
y <- LIDAR_data [,2]
z <- LIDAR_data [,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
## The function is currently defined as
Extract_plant_grapevine_function <- function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz){
y <- -y
y <- y-min(y)
z<- (z*zdistance)/max(z)
x_cm <- 0
y_cm <- 0
z_cm <- 0
for (i in 1:length(x)){
if (x[i] >= minx && x[i] <= maxx && y[i] >= miny && y[i] <= maxy && z[i] >= minz && z[i] <= maxz) {
y_cm[i] <- y[i]
x_cm[i] <- x[i]
z_cm[i] <- z[i]
}
}
y_cm <- na.omit(y_cm[2:length(y_cm)])
y_cm <- as.numeric((y_cm-min(y_cm))/1000)
x_cm <- as.numeric(na.omit(x_cm[2:length(x_cm)])/1000)
z_cm <- as.numeric(na.omit(z_cm[2:length(z_cm)])/100)
return <- data.frame(x_cm,y_cm,z_cm)
}
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
x = out[,1]
y = out[,2]
z = out[,3]4
Extract_plant_3D_function
# plot
par(mfcol=c(2,2))
plot(x,y,pch=20,cex=.4,xlab='Width (m)', ylab='Height (m)', main='Grapevine BBCH')
plot(x,z,pch=20,cex=.4,xlab='Width (m)', ylab='Front (m)', main='Grapevine BBCH')
plot(z,y,pch=20,cex=.4,xlab='Front (m)', ylab='Height (m)', main='Grapevine BBCH')
Extract_plant_3D_function
Extract plant 3D (grapevine).

#### Description 

This function move the axes x,y,z to the center of the plant. This output could be exported and
transformed in GRASS GIS in 3D maps.

#### Usage 

Extract_plant_3D_function(out, z_min, z_max, y_min, y_max, distance_left, distance_right)

#### Arguments 

out out is a data frame output from Extract_plant_grapevine_function.
* ``z_min``: the minimum position of the stem in z measured in meters.
* ``z_max``: the maximum position of the stem in z measured in meters.
* ``y_min``: the minimum position of the stem in y measured in meters.
* ``y_max``: the maximum position of the stem in y measured in meters.
* ``distance_left``:  the left distancethe left distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
* ``distance_right``:  the right distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

## Should be DIRECTLY executable !!
## out come from Extract_plant_grapevine_function. The other parameters or inputs are needed to write before.
## For example:
data (LIDAR_data)
x <- LIDAR_data[,1]
y <- LIDAR_data[,2]
z <- LIDAR_data[,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.Extract_plant_grapevine_function
5
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
z_min <- 1.1
z_max <- 1.13
y_min <- 0.4
y_max <- 0.5
* ``distance_left``:  the left distance<- -0.6
distance_right <- 0.51
## The function is currently defined as
Extract_plant_3D_function <- function(out,z_min,z_max,y_min,y_max,distance_left,distance_right){
x_cm <- y_cm <- z_cm <- NULL
data_stem <- subset(out,out$y_cm > y_min & out$y_cm<= y_max & out$z_cm >= z_min & out$z_cm <= z_max,select=c(x_
x_c
<- out$x_cm - min(data_stem$x_cm)
y_c
<- out$y_cm
z_c
<- out$z_cm - min(data_stem$z_cm)
data_cero <- data.frame(x_c,y_c,z_c)
data_plant <- subset(data_cero, data_cero$z_c >= * ``distance_left``:  the left distance& data_cero$z_c <= distance_right,select=c(x_c,y
x_plant <- data_plant[,1]
y_plant <- data_plant[,2]
z_plant <- data_plant[,3]
return(data.frame(x_plant,y_plant,z_plant))
}
data_3D <- Extract_plant_3D_function(out,z_min,z_max,y_min,y_max,distance_left,distance_right)
x_plant <- data_3D[,1]
y_plant <- data_3D[,2]
z_plant <- data_3D[,3]
# plot
par(mfcol=c(2,2))
plot(x_plant,y_plant,pch=20,cex=.4)
plot(x_plant,z_plant,pch=20,cex=.4)
plot(z_plant,y_plant,pch=20,cex=.4)
