LIDAR data.

Replicate plants function.

#### Description 

This function helped to make 3D maps in GRASS GIS when you have only one scan of a plant.
First needed rotate the plants and them could be replicate each plant in the row.

#### Usage 

Replicate_plants_function(plants_rotate, data_3D, latitude, longitude)

#### Arguments 

plants_rotate here need use the output of Rotate_function.
data_3D here need use the output of Exract_plant_3D_function and Extract_plant_grapevine_function.
latitude here need the latitudine of each plant.
longitude here need the longitude of each plant.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

## Should be DIRECTLY executable !!
## out come from Extract_plant_grapevine_function. The other parameters or inputs are needed to write before.
## For example:
data (LIDAR_data)
x <- LIDAR_data[,1]
y <- LIDAR_data[,2]14
Rotate_function
z <- LIDAR_data[,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
z_min <- 1.1
z_max <- 1.13
y_min <- 0.4
y_max <- 0.5
* ``distance_left``:  the left distance<- -0.6
distance_right <- 0.51
data_3D <- Extract_plant_3D_function(out,z_min,z_max,y_min,y_max,distance_left,distance_right)
latitude <- c(396626.74528,396627.689076,396628.632872,396629.576669,396630.520465)
longitude <- c(4566489.007441,4566490.032831,4566491.058221,4566492.083612,4566493.109002)
angle <- 14.96
plants_rotate <- Rotate_function(data_3D,angle)
## The function is currently defined as
Replicate_plants_function <- function(plants_rotate,data_3D,latitude,longitude){
x_rot <- plants_rotate[,1]
y_rot <- plants_rotate[,2]
z
<- data_3D[,2]
rep_z <- rep(z,length(latitude))
rep_X <- rep(x_rot,length(latitude))
rep_Y <- rep(y_rot,length(latitude))
dup_xcoord <- rep(latitude ,each=length(x_rot))
dup_ycoord <- rep(longitude,each=length(y_rot))
XCOORD <- rep_X + dup_xcoord
YCOORD <- rep_Y + dup_ycoord
return (data.frame(XCOORD,YCOORD,z))
}
rep <- Replicate_plants_function(plants_rotate,data_3D,latitude,longitude)
X <- rep[,1]
Y <- rep[,2]
Z <- rep[,3]
## plot
par(mfcol=c(1,2))
plot(X,Y)
plot(X,Z)
Rotate_function
Rotate the plants.

#### Description 

The function help in rotate the plants to match with the planting line.Rotate_function
15

#### Usage 

Rotate_function(data_3D, angle)

#### Arguments 

* ``data_3D``:  ``data_3D`` is the output of Extract_plant_3D_function.
angle angle is one value like 14.96 degree that needed rotate the plants.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 

## Should be DIRECTLY executable !!
## out come from Extract_plant_grapevine_function. The other parameters or inputs are needed to write before.
## For example:
data (LIDAR_data)
x <- LIDAR_data[,1]
y <- LIDAR_data[,2]
z <- LIDAR_data[,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.
maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
z_min <- 1.1
z_max <- 1.13
y_min <- 0.4
y_max <- 0.5
* ``distance_left``:  the left distance<- -0.6
distance_right <- 0.51
data_3D <- Extract_plant_3D_function(out,z_min,z_max,y_min,y_max,distance_left,distance_right)
angle <- 14.96
## The function is currently defined as
Rotate_function <- function(data_3D,angle){
z <- -data_3D[,3]
x <- data_3D[,1]
x_rot <-c(x*cos(angle)-z*sin(angle))
y_rot <-c(x*sin(angle)+z*cos(angle))
return(data.frame(x_rot,y_rot))
}
Plants_rotate <- Rotate_function(data_3D,angle)
x_rot <- Plants_rotate[,1]
y_rot <- Plants_rotate[,2]
##plot
plot(x_rot,y_rot)16
TRV_lidar_function
TRV_lidar_function
Tree Row Volume (TRV).

#### Description 

TRV measured in m^3*ha^-1.

#### Usage 

TRV_lidar_function(height_canopy, width_canopy, row_spacing)

#### Arguments 

height_canopy use Height_canopy_function, measured in meters.
width_canopy use Width_canopy_function, measured in meters.
row_spacing row spacing measured in meters.

#### Authors(s) 

Monica Fernanda Rinaldi

#### References 

Byers, R.E., 1987. Tree-row-volume Spraying Rate Calculator for Apples. HortScience 22, 506-
507.
* Gil, E., Escola, A., Rosell, J.R., Planas, S., Val, L., 2007. Variable rate application of plant protec-
tion products in vineyard using ultrasonic sensors. Crop Prot. 26, 1287-1297.
* Gil, E., Escola, A., 2009. Design of a Decision Support Method to Determinate Volume Rate for
Vineyard Spraying. ASABE. 25, 145-151.

#### Examples 

## Should be DIRECTLY executable !! ----
## Here need use: Height_canopy_function and Width_canopy_function or values measured manually.
height_canopy <- 1.995 ## the value is the result of Height_canopy_function.
width_canopy <- 0.426 ## the value is the result of Width_canopy_function.
row_spacing = 2.9 ## measured in meters.
## The function is currently defined as
TRV_lidar_function <- function(height_canopy,width_canopy,row_spacing){
TRV <-height_canopy * width_canopy * 10000 / row_spacing
return(TRV)
}
TRV <- TRV_lidar_function(height_canopy,width_canopy,row_spacing)Width_canopy_function
17
Width_canopy_function Canopy width measured with LIDAR.

#### Description 

From the LIDAR dataset can be calculate the width of the grapevine plant.The function returns the
average, minimum and maximum value of the width measured in meters.

#### Usage 

Width_canopy_function(data_3D, distance_left, distance_right, min_canopy, max_canopy)

#### Arguments 

data_3D Here need use the output of the Extract_plant_3D_function
* ``distance_left``:  the left distancethe left distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
* ``distance_right``:  the right distance of the plant, generally here we can write the half of the dis-
tance between plants, but is better the real distance from the center of the plant.
Measured in meters.
min_canopy the minimum height of the canopy, measured in meters.
max_canopy the maximum height of the canopy, measured in meters.

#### Details 

Maximum and minimum values of height of canopy could be approximative values.

#### Authors(s) 

Monica Fernanda Rinaldi

#### Examples 
<pre><code>
## Should be DIRECTLY executable !! ----
## Data_3D is the output from the Extrac_plant_3D_function.
## For example:
data (LIDAR_data)
x <- LIDAR_data[,1]
y <- LIDAR_data[,2]
z <- LIDAR_data[,3]
zdistance <- 190 # total LIDAR scan distance measured in cm.
miny <- 0 # minimum height of the plant measured in cm.
maxy <- 2000 # maximum height of the plant measured in cm.
minx <- 450 # minimum width from where LIDAR starts to measure (cm).
maxx <- 1470# maximum width from where LIDAR starts to measure (cm).
minz <- 0 # the beginning of the LIDAR scan measured in cm.18

maxz <- 186 # the end of the LIDAR scan measured in cm (length of interest).
out <- Extract_plant_grapevine_function(x,y,z,zdistance,miny,maxy,minx,maxx,minz,maxz)
z_min <- 1.1
z_max <- 1.13
y_min <- 0.4
y_max <- 0.5
* ``distance_left``:  the left distance<- -0.6
distance_right <- 0.51
data_3D <- Extract_plant_3D_function(out,z_min,z_max,y_min,y_max,distance_left,distance_right)
min_canopy <- 0.4 # is the minimum height of the canopy, approximately . Measured in meters.
max_canopy <- 2 # is the maximum height of the canopy, approximately . Measured in meters.
## The function is currently defined as
Width_canopy_function <- function(data_3D,distance_left,distance_right,min_canopy,max_canopy){
x_plant <- y_plant <- z_plant <- NULL
canopy <- subset(data_3D, data_3D$z_plant >= * ``distance_left``:  the left distance& data_3D$z_plant <= distance_right & data_3D$y_plan
mean_width_canopy <- mean(abs(canopy[,1]))
min_width_canopy <- min(abs(canopy[,1]))
max_width_canopy <- max(abs(canopy[,1]))
return(data.frame(mean_width_canopy,min_width_canopy,max_width_canopy))
}
width_canopy <- Width_canopy_function(data_3D,distance_left,distance_right,min_canopy,max_canopy)[,1]
</code></pre>
