forestinventory: Design-Based Global and Small-Area Estimations for Multiphase Forest Inventories
======================================================================================
Extensive global and small-area estimation procedures for multiphase forest inventories under the design-based Monte-Carlo 
approach are provided. 

The implementation includes estimators for simple and cluster sampling published by Daniel Mandallaz 
in 2007 (<doi:10.1201/9781584889779>), 2013 (<doi:10.1139/cjfr-2012-0381>, <doi:10.1139/cjfr-2013-0181>,
<doi:10.1139/cjfr-2013-0449>, <doi:10.3929/ethz-a-009990020>) and 2016 (<doi:10.3929/ethz-a-010579388>). 
It provides point estimates, their external- and design-based variances as well as confidence intervals. 
The procedures have also been optimized for the use of remote sensing data as auxiliary information.

forestinventory: A package for computing design-based estimates for
multiphase forest inventories

#### Description
The package provides global- and smallarea estimators for twophase and threephase forest in-
ventories under simple and cluster sampling, which have been developed by Daniel * Mandallaz at
ETH Zurich. The implemented methods have been published and applied in various studies (see References) and can be used for double- and triple sampling for stratification, double- and triple
sampling for regression and double- and triple sampling for regression within strata.
Functions
The package provides three main functions to apply the various estimators for twophase and three-
phase forest inventories:
*  twophase Function to apply global- and various smallarea estimation techniques for twophase
inventories
*  threephase Function to apply global- and various smallarea estimation techniques for three-
phase inventories
*  onephase Function to apply estimations for onephase inventories, mainly for comparison with
two-and threephase

#### Motivation
The Motivation of writing this package was to provide an extensive and consistent collection of
state-of-the-art design-based estimation techniques for forest inventories. It was especially designed
to facilitate the application of the available estimators in forest practice as well as in scientifically
related studies. The work on this package was also the trigger to complete the range of the allready
published estimators, especially in the framework of three-phase smallarea estimators.
 
#### Selected References
Massey, A. F. (2015). Multiphase estimation procedures for forest inventories under the design-
based Monte Carlo approach (Doctoral dissertation, Diss., ETH Zurich, Nr. 23025).
* Mandallaz, D. (2013). Design-based properties of some small-area estimators in forest inventory
with two-phase sampling. Canadian Journal of Forest Research, 43(5), 441-449.
* Mandallaz, D., Breschan, J., & Hill, A. (2013). New regression estimators in forest inventories with
two-phase sampling and partially exhaustive information: a design-based monte carlo approach
with applications to small-area estimation. Canadian Journal of Forest Research, 43(11), 1023-
1031.
* Mandallaz, D. (2013). A three-phase sampling extension of the generalized regression estimator
with partially exhaustive information. Canadian Journal of Forest Research, 44(4), 383-388.8
